Finding out the performance of region

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\Talib\Desktop\DA - Projects\New Project Resume\Dataset\files v2\Cleaned Data\Fact_Sales.csv")
df

,Row_ID,Order_ID,Date_ID,Order_Date,Ship_Date,Delivery_Duration(Days),Ship_Mode,Customer_ID,Product_ID,Quantity,Unit_Price_BDT,Discount_Pct,Sales_BDT,Cost_BDT,Profit_BDT,Profit_Margin_Pct,Payment_Method,Is_Returned
0,1,ORD-105638,DATE-20230101,01-01-23,02-01-23,1,Standard,CUS-02321,PROD-00001,8,4771.66,0.042,36570.00,34620.64,1949.36,5.33,Cash on Delivery,False
1,2,ORD-102334,DATE-20230101,01-01-23,02-01-23,1,Standard,CUS-01456,PROD-00002,3,11470.75,0.100,30971.03,22946.73,8024.30,25.91,bKash,True
2,3,ORD-100570,DATE-20230101,01-01-23,08-01-23,7,Standard,CUS-00028,PROD-00003,11,58.85,0.077,597.50,548.44,49.06,8.21,Cash on Delivery,False
3,4,ORD-101183,DATE-20230101,01-01-23,02-01-23,1,Standard,CUS-00412,PROD-00004,4,11474.86,0.099,41355.40,38073.88,3281.52,7.93,bKash,False
4,5,ORD-104389,DATE-20230101,01-01-23,03-01-23,2,Standard,CUS-01955,PROD-00005,4,1722.10,0.196,5538.27,5080.03,458.24,8.27,Cash on Delivery,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9085,9086,ORD-103318,DATE-20251230,30-12-25,04-01-26,5,Standard,CUS-00533,PROD-07713,3,49009.23,0.052,139382.25,134636.13,4746.12,3.41,Cash on Delivery,False
9086,9087,ORD-108236,DATE-20251231,31-12-25,02-01-26,2,Same-Day,CUS-00895,PROD-01022,1,4270.98,0.213,3361.26,2882.84,478.42,14.23,bKash,False
9087,9088,ORD-106406,DATE-20251231,31-12-25,05-01-26,5,Standard,CUS-01913,PROD-02484,3,43433.88,0.051,123656.26,119053.06,4603.20,3.72,Cash on Delivery,False
9088,9089,ORD-103140,DATE-20251231,31-12-25,02-01-26,2,Standard,CUS-01687,PROD-07714,11,644.09,0.596,2862.34,-297.56,3159.90,110.40,Credit/Debit Card,False
9089,9090,ORD-108240,DATE-20251231,31-12-25,05-01-26,5,Standard,CUS-01045,PROD-07480,2,5692.56,0.070,10588.16,7551.98,3036.18,28.68,Credit/Debit Card,True

In [3]:
customer = pd.read_csv(r"C:\Users\Talib\Desktop\DA - Projects\New Project Resume\Dataset\files v2\Cleaned Data\Dim_Customer.csv")
customer

     Customer_ID Segment    Division     District
0      CUS-00001     B2C       Dhaka  Narayanganj
1      CUS-00002     B2C  Mymensingh     Jamalpur
2      CUS-00003     B2C      Khulna      Jessore
3      CUS-00005     B2C  Mymensingh   Mymensingh
4      CUS-00008     B2C  Chittagong         Feni
...          ...     ...         ...          ...
1497   CUS-02591     B2C  Chittagong   Chittagong
1498   CUS-02592     B2C       Dhaka  Narayanganj
1499   CUS-02594     B2B      Khulna       Khulna
1500   CUS-02596     B2C       Dhaka  Narayanganj
1501   CUS-02599     B2C       Dhaka      Tangail

[1502 rows x 4 columns]

In [4]:
df_customer = df.merge(
    customer[['Customer_ID', 'Segment', 'Division', 'District']],
    on='Customer_ID',
    how='left'
)

print(df_customer.columns)

Index(['Row_ID', 'Order_ID', 'Date_ID', 'Order_Date', 'Ship_Date',
       'Delivery_Duration(Days)', 'Ship_Mode', 'Customer_ID', 'Product_ID',
       'Quantity', 'Unit_Price_BDT', 'Discount_Pct', 'Sales_BDT', 'Cost_BDT',
       'Profit_BDT', 'Profit_Margin_Pct', 'Payment_Method', 'Is_Returned',
       'Segment', 'Division', 'District'],
      dtype='str')

Regional Performance & Profitability Breakdown by Division

In [5]:

division_analysis = (
    df_customer.groupby('Division')
    .agg(
        Revenue=('Sales_BDT', 'sum'),
        Cost=('Cost_BDT', 'sum'),
        Profit=('Profit_BDT', 'sum'),
        Quantity=('Quantity', 'sum')
    )
    .reset_index()
)

division_analysis['Margin_Pct'] = (
    division_analysis['Profit'] /
    division_analysis['Revenue'] * 100
)

division_analysis['Revenue_Share_Pct'] = (
    division_analysis['Revenue'] /
    division_analysis['Revenue'].sum() * 100
)

division_analysis['Profit_Share_Pct'] = (
    division_analysis['Profit'] /
    division_analysis['Profit'].sum() * 100
)

print(
    division_analysis
    .sort_values('Profit', ascending=False)
    .round(2)
)

     Division       Revenue          Cost       Profit  Quantity  Margin_Pct  \
2       Dhaka  1.120431e+08  1.015947e+08  10448431.80     22948        9.33
1  Chittagong  6.322784e+07  5.767291e+07   5586442.71     10014        8.84
3      Khulna  3.558769e+07  3.227147e+07   3316220.58      6628        9.32
5    Rajshahi  1.575808e+07  1.402587e+07   1732202.39      3450       10.99
7      Sylhet  1.598158e+07  1.428692e+07   1694653.65      3095       10.60
0    Barishal  1.399921e+07  1.274660e+07   1252607.15      2713        8.95
6     Rangpur  9.212470e+06  8.345062e+06    867408.33      1343        9.42
4  Mymensingh  1.042082e+07  9.592358e+06    828465.16      2013        7.95

   Revenue_Share_Pct  Profit_Share_Pct
2              40.56             40.61
1              22.89             21.71
3              12.88             12.89
5               5.70              6.73
7               5.79              6.59
0               5.07              4.87
6               3.34              3.37
4               3.77              3.22

Best Region/Division

In [6]:
print("TOP DIVISIONS BY PROFIT")

print(
    division_analysis
    .sort_values('Profit', ascending=False)
    .head(3)
    .round(2)
)

TOP DIVISIONS BY PROFIT
     Division       Revenue          Cost       Profit  Quantity  Margin_Pct  \
2       Dhaka  1.120431e+08  1.015947e+08  10448431.80     22948        9.33
1  Chittagong  6.322784e+07  5.767291e+07   5586442.71     10014        8.84
3      Khulna  3.558769e+07  3.227147e+07   3316220.58      6628        9.32

   Revenue_Share_Pct  Profit_Share_Pct
2              40.56             40.61
1              22.89             21.71
3              12.88             12.89

Worst Margin Region

In [7]:
print("\nLOWEST MARGIN DIVISIONS")

print(
    division_analysis
    .sort_values('Margin_Pct')
    .head(3)
    .round(2)
)

LOWEST MARGIN DIVISIONS
     Division      Revenue         Cost      Profit  Quantity  Margin_Pct  \
4  Mymensingh  10420823.06   9592357.90   828465.16      2013        7.95
1  Chittagong  63227838.08  57672906.74  5586442.71     10014        8.84
0    Barishal  13999209.83  12746602.68  1252607.15      2713        8.95

   Revenue_Share_Pct  Profit_Share_Pct
4               3.77              3.22
1              22.89             21.71
0               5.07              4.87

HIGH-REVENUE BUT LOW-MARGIN DIVISIONS

In [8]:
high_revenue_low_margin_region = division_analysis[
    (division_analysis['Revenue'] >= division_analysis['Revenue'].median()) &
    (division_analysis['Margin_Pct'] <= division_analysis['Margin_Pct'].median())
]

print("\nHIGH-REVENUE BUT LOW-MARGIN DIVISIONS")

print(
    high_revenue_low_margin_region
    .sort_values('Revenue', ascending=False)
    .round(2)
)

HIGH-REVENUE BUT LOW-MARGIN DIVISIONS
     Division      Revenue         Cost      Profit  Quantity  Margin_Pct  \
1  Chittagong  63227838.08  57672906.74  5586442.71     10014        8.84
3      Khulna  35587692.78  32271472.20  3316220.58      6628        9.32

   Revenue_Share_Pct  Profit_Share_Pct
1              22.89             21.71
3              12.88             12.89